#!/usr/bin/env sh

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")
PATTERN="^(init|feat|fix|docs|refactor|config|style|test):.*+$"

if ! echo $COMMIT_MSG | grep -Eq $PATTERN; then
  echo "Invalid commit message format!"
  exit 1
fi